-- Test data for fabrics
-- Insert sample fabrics for testing

INSERT INTO fabrics (
  name, 
  code, 
  description, 
  material, 
  width, 
  weight, 
  color, 
  pattern, 
  finish, 
  origin,
  price_per_meter, 
  stock_quantity, 
  min_order_quantity,
  primary_image_url,
  tags
) VALUES 
(
  'Vải Lụa Cotton - F0123',
  'F0123',
  'Vải sự pha trộn sang trọng giữa lụa và các sợi cotton nhẹ nhàng, mang lại cảm giác mềm mại và thoáng mát. Lý tưởng cho các thiết kế thời trang cao cấp và trang sức nội thất.',
  '70% Lụa, 30% Cotton',
  140,
  120,
  'Trắng ngà',
  'Trơn',
  'Satin',
  'Ý',
  45.00,
  500,
  5,
  'https://images.unsplash.com/photo-1558769132-cb1aea1f5d7e?w=800',
  ARRAY['cao cấp', 'mềm mại', 'sang trọng']
),
(
  'Vải Cotton Organic - F0124',
  'F0124',
  'Vải cotton hữu cơ 100% thân thiện với môi trường, được dệt từ sợi cotton tự nhiên không qua xử lý hóa học. Phù hợp cho quần áo trẻ em và người có da nhạy cảm.',
  '100% Cotton Organic',
  150,
  180,
  'Xanh navy',
  'Kẻ sọc',
  'Mềm',
  'Việt Nam',
  28.50,
  800,
  10,
  'https://images.unsplash.com/photo-1519710164239-da123dc03ef4?w=800',
  ARRAY['organic', 'thân thiện môi trường', 'cotton']
),
(
  'Vải Linen Cao Cấp - F0125',
  'F0125',
  'Vải lanh cao cấp với độ bền vượt trội và khả năng thấm hút tốt. Chất liệu tự nhiên mang lại cảm giác mát mẻ, lý tưởng cho thời tiết nóng ẩm.',
  '100% Linen',
  135,
  200,
  'Be',
  'Trơn',
  'Tự nhiên',
  'Pháp',
  52.00,
  300,
  5,
  'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800',
  ARRAY['linen', 'mát mẻ', 'cao cấp']
),
(
  'Vải Polyester In Hoa - F0126',
  'F0126',
  'Vải polyester với họa tiết hoa văn tinh tế, màu sắc bền đẹp và dễ bảo quản. Thích hợp cho may áo dài, váy dạ hội và trang trí nội thất.',
  '100% Polyester',
  145,
  150,
  'Đỏ',
  'Hoa văn',
  'In kỹ thuật số',
  'Trung Quốc',
  18.00,
  1200,
  20,
  'https://images.unsplash.com/photo-1492707892479-7bc8d5a4ee93?w=800',
  ARRAY['polyester', 'họa tiết', 'dễ bảo quản']
),
(
  'Vải Wool Blend - F0127',
  'F0127',
  'Vải len pha với độ ấm tốt và khả năng giữ form dáng cao. Chất liệu cao cấp phù hợp cho áo khoác, vest và trang phục mùa đông.',
  '80% Wool, 20% Polyester',
  150,
  280,
  'Xám',
  'Trơn',
  'Dệt kim',
  'Anh',
  68.00,
  200,
  3,
  'https://images.unsplash.com/photo-1558769132-cb1aea1f5d7e?w=800',
  ARRAY['wool', 'ấm áp', 'cao cấp']
);

